services:
  gitea:
    environment:
      VIRTUAL_PORT: ${VIRTUAL_PORT:-3000}
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      ROOT_URL: ${ROOT_URL}
    networks:
      - letsencrypt-network

networks:
  letsencrypt-network:
    external: true
